arrowParens: avoid
bracketSpacing: true
endOfLine: auto
printWidth: 120
singleQuote: false
tabWidth: 2
trailingComma: all

overrides:
  - files: "*.sol"
    options:
      compiler: "0.8.18"
      tabWidth: 4
      printWidth: 80
      singleQuote: false
      bracketSpacing: false
  - files: "*.ts"
    options:
      tabWidth: 4
      printWidth: 80
      importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
      importOrderParserPlugins: ["typescript"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true